### ISSUE TITLE
Settings / Dashboard unavailable

### ISSUE THREAD

**Issue by iKurama** [gw2mists/issues#2]
I have logged in, but when I try to edit the stuff in settings, which I could prior to the new design, this happens.
![bpAmydbyRJ](https://user-images.githubusercontent.com/7503922/99887952-e9665f80-2c48-11eb-8b3b-252a043f8072.gif)

However, when I go to https://gw2mists.com/dashboard (still, without adblock or any extension whatsoever), 
![firefox_7Ba9YuE0Nr](https://user-images.githubusercontent.com/7503922/99887974-20d50c00-2c49-11eb-9566-ad4c25365f54.png) It gives me that.

This is where it gets interesting. Tried to clear cache. Nothing happened, tried to change DNS, nothing happened, VPN and nothing happened.
I tried to switch _from_ Firefox (latest) to Google Chrome. It allowed me.
[HOWEVER, once closing chrome down and opening it again, Chrome blocks me out of it. It will eventually load part of the dashboard, after 1125 errors.]
This is where the fun begins, my friend who's new to it, has the opposite problem, where their chrome doesn't work with it.

Inspect picture added, in case of relevance
![firefox_sWmB9NKmfa](https://user-images.githubusercontent.com/7503922/99888041-a35dcb80-2c49-11eb-87ac-1883d935703e.png)
And for error part
![image](https://user-images.githubusercontent.com/7503922/99888100-529aa280-2c4a-11eb-8d92-c4a3ca2dce9e.png)
![image](https://user-images.githubusercontent.com/7503922/99888110-6514dc00-2c4a-11eb-8e2e-900bebd0a5ea.png)

**Comment by bessgeor** [comment]
I've faced the unavailability just after the registration I've completed (or at least it looked like a completion). There were some tries before the screenshot, I think they've failed because very long requests to /locales/**.json and /matomo/piwik.php - it seems like browser queued the other requests because of simultaneous requests limit and that requests have timed out.
![image](https://user-images.githubusercontent.com/2414765/100880870-54702b80-34be-11eb-9e6b-995c782fd97f.png)

**Comment by bessgeor** [comment]
My issue was resolved by the following steps:
1. Delete all cookies except for the "general" one
2. Open sign-in page in new tab (using the link from header on the Christmas Lottery  page)
3. Sign-in
4. Go to account settings -> api-keys
The actions above allowed me to see the api keys page and enter one

**Comment by iKurama** [comment]
The issue solved itself for me, after Aros upgraded the server.
